2022-05-19 19:49:20, Exception thrown: Connection to database failed
se.kth.iv1350.pos.integration.InventoryException: Connection to database failed
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:87)
	at se.kth.iv1350.pos.integration.Inventory.findItem(Inventory.java:42)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:52)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:34)
Caused by: java.sql.SQLException
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:76)
	... 4 more
2022-05-19 19:49:20, Exception thrown: Connection to database failed
se.kth.iv1350.pos.integration.InventoryException: Connection to database failed
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:87)
	at se.kth.iv1350.pos.integration.Inventory.findItem(Inventory.java:42)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:63)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:34)
Caused by: java.sql.SQLException
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:76)
	... 4 more
2022-05-19 19:49:22, Exception thrown: Connection to database failed
se.kth.iv1350.pos.integration.InventoryException: Connection to database failed
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:87)
	at se.kth.iv1350.pos.integration.Inventory.findItem(Inventory.java:42)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:52)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:34)
Caused by: java.sql.SQLException
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:76)
	... 4 more
2022-05-19 19:49:22, Exception thrown: Connection to database failed
se.kth.iv1350.pos.integration.InventoryException: Connection to database failed
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:87)
	at se.kth.iv1350.pos.integration.Inventory.findItem(Inventory.java:42)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:63)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:34)
Caused by: java.sql.SQLException
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:76)
	... 4 more
2022-05-19 19:49:23, Exception thrown: Connection to database failed
se.kth.iv1350.pos.integration.InventoryException: Connection to database failed
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:87)
	at se.kth.iv1350.pos.integration.Inventory.findItem(Inventory.java:42)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:52)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:34)
Caused by: java.sql.SQLException
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:76)
	... 4 more
2022-05-19 19:49:23, Exception thrown: Connection to database failed
se.kth.iv1350.pos.integration.InventoryException: Connection to database failed
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:87)
	at se.kth.iv1350.pos.integration.Inventory.findItem(Inventory.java:42)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.pos.view.View.runFakeExecution(View.java:63)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:34)
Caused by: java.sql.SQLException
	at se.kth.iv1350.pos.integration.Inventory.checkForMatchingItemInInventory(Inventory.java:76)
	... 4 more
